def raise_exception():
    return("Hello" + 5)
